// beer/projects/kegberry-app/src/app/views/statistics.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'statistics',
    templateUrl: 'statistics.component.html',
    styleUrls: ['statistics.component.css']
})
export class StatisticsComponent {}
<a routerLink="/" routerLinkActive="active">
    <div class="user-icon">
            <img class="user-icon"
                [src]="'assets/users.png'">
    </div>
</a>
<leaderboard></leaderboard>
<brewery-mixer class="brewery"></brewery-mixer>

// beer2/src/components/Statistics/Statistics.tsx
import React, { Fragment } from 'react';
import { Leaderboard } from '../Leaderboard/Leaderboard';
import './Statistics.css';
import { Link } from 'react-router-dom';
import users from '../../assets/users.png';

export function Statistics() {
  return (
    <Fragment>
      <Link to='/'>
        <div className='home-icon'>
          <img className='home-icon'
              src={users}
              alt='Home'/>
        </div>
      </Link>
      <Leaderboard/>
    </Fragment>
  );
}
