// beer/app/views/add-user-dialog.component.ts
import { Component, OnInit, Injectable, Output, EventEmitter } from '@angular/core';
import { MessagingService } from '../infrastructure/messaging.service';

@Component({
    selector: 'add-user-dialog',
    templateUrl: './app/views/add-user-dialog.component.html',
    styleUrls: ['./app/views/add-user-dialog.component.css']
})
export class AddUserDialogComponent implements OnInit {
    private _usernameInput: string = "";

    @Output() commit = new EventEmitter<string>();
    @Output() cancel = new EventEmitter<any>();

    constructor(@Injectable() private _messagingService: MessagingService) {}

    ngOnInit(): void { }

    onCommit() {
        this.commit.emit(this._usernameInput);
    }

    onCancel() {
        this.cancel.emit(undefined);
    }

    onKey(event: any) {
        this._usernameInput = event.target.value;
    }
}

<label class="username-label">What's your name?</label>
<input type="username" (keyup)="onKey($event)">
<div class="action-buttons">
    <button class="cancel-button" (click)="onCancel()">Cancel</button>
    <button class="commit-button" (click)="onCommit()">Ok</button>
</div>

// beer2/src/components/AddUserDialog/AddUserDialog.tsx
import React, { useState, useCallback } from 'react';
import './AddUserDialog.css';

export interface IAddUserDialogProps {
  onCommit(username: string): void;
  onCancel(): void;
}

export function AddUserDialog(props: IAddUserDialogProps) {
  const [usernameInput, setUsernameInput] = useState('');
  const handleOnKeyUp = useCallback((event: any) => setUsernameInput(event.target.value), []);

  return (
    <div className='add-user-dialog'>
      <label className='username-label'>What's your name?</label>
      <input type='username' placeholder='Type Name' onKeyUp={handleOnKeyUp}/>
      <div className='action-buttons'>
          <button className='cancel-button' onClick={props.onCancel}>Cancel</button>
          <button className='commit-button' onClick={() => { props.onCommit(usernameInput) }}>Ok</button>
      </div>
    </div>
  );
}
