// beer2/src/components/Home/Home.tsx
import React, { useState, useEffect } from 'react';
import { useMessagingService } from '../../infrastructure/MessagingContext';
import './Home.css';
import { Users } from '../Users/Users';
import { Pouring } from '../Pouring/Pouring';


export const Home = (props: any) => {
  const messagingService = useMessagingService();
  const [pouring, setPouring] = useState(false);
  const onUserSelected = () => {
    setPouring(true);
  };

  const onPourFinished = () => {
    setPouring(false);
  };

  useEffect(() => {
    const subscription = messagingService.currentUserTimeoutNotification$
      .subscribe(_ => {
        setPouring(false)
    });

    return () => subscription.unsubscribe();
  },
  [messagingService
    .currentUserTimeoutNotification$]);

  return (
    <div className="home">
      {!pouring &&
        <Users onUserSelected={onUserSelected}>
        </Users>
      }
      {pouring &&
        <Pouring pourFinished={onPourFinished}>
        </Pouring>
      }
    </div>
  )
}

// beer/projects/kegberry-app/src/app/views/home.component.ts
import { Component } from '@angular/core';
import { MessagingService, ITemperatureNotification, IUser } from './../infrastructure/messaging.service';
import { Observable } from 'rxjs';

@Component({
  selector: 'home',
  templateUrl: 'home.component.html',
  styleUrls: ['home.component.css']
})

export class HomeComponent {
  pouring: boolean = false;

  constructor(private messageService: MessagingService) {}

  ngOnInit(): void {
    this.messageService.currentUserTimeoutNotification$.subscribe(_ => {
      this.pouring = false;
    });
  }

  onUserSelected(user: IUser) {
    this.pouring = true;
  }

  onPourFinished(_) {
    this.pouring = false;
  }

}

<div class="home">
    <users-component *ngIf="!this.pouring"
        (userSelected)="onUserSelected($event)">
    </users-component>
    <pouring *ngIf="this.pouring"
        (pourFinished)="onPourFinished($event)">
    </pouring>
</div>
