// beer2/src/components/Users/Users.tsx
import React, { useState, useEffect, Fragment } from 'react';
import { useMessagingService } from '../../infrastructure/MessagingContext';
import { GetUsers, IGetUserResponse, IUser, IAddUserMessageData, AddUser, SelectUser, ISelectUserData } from '../../infrastructure/MessagingService';
import './Users.css';
import add_user from '../../assets/add_user.png';
import stats from '../../assets/stats.png';
import profile0 from '../../assets/profile_0.png'
import profile1 from '../../assets/profile_1.png'
import profile2 from '../../assets/profile_2.png'
import profile3 from '../../assets/profile_3.png'
import profile4 from '../../assets/profile_4.png'
import profile5 from '../../assets/profile_5.png'
import profile6 from '../../assets/profile_6.png'
import profile7 from '../../assets/profile_7.png'
import profile8 from '../../assets/profile_8.png'
import profile9 from '../../assets/profile_9.png'
import { AddUserDialog } from '../AddUserDialog/AddUserDialog';
import { Link } from 'react-router-dom';

const profileImages = [
  profile0,
  profile1,
  profile2,
  profile3,
  profile4,
  profile5,
  profile6,
  profile7,
  profile8,
  profile9
];

export interface IUsersProps {
  onUserSelected: () => void;
}

export const Users = (props: any) => {
  const messagingService = useMessagingService();
  const [users, setUsers] = useState<IUser[]>([]);
  const [selectedUserId, setSelectedUserId] = useState('');
  const [addUserDialogActive, setAddUserDialogActive]  = useState(false);

  function addUser(username: string): void {
    let data: IAddUserMessageData = {name: username};
    messagingService.sendMessage(AddUser, data);
  }

  function onUserSelected(user: IUser): void {
    let data: ISelectUserData = {id: user.id};
    messagingService.sendMessage(SelectUser, data);
    setSelectedUserId(user.id);
    props.onUserSelected();
  }

  function onAddUserCommit(username: string) {
      setAddUserDialogActive(false);
      addUser(username);
  }

  function onAddUserCancel() {
    setAddUserDialogActive(false);
  }

  function onAddUser() {
    setAddUserDialogActive(true);
  }

  useEffect(() => {
    const subscriptions = [
      messagingService.readyStream.subscribe(() => {
        messagingService.sendMessage(GetUsers, undefined);
      }),
      messagingService.getUsersResponseStream.subscribe((response: IGetUserResponse|undefined) => {
        if (response !== undefined) {
            setUsers(response.users);
        }
      }),
      messagingService.addUserResponseStream.subscribe((user: IUser) => {
        if (user !== undefined || user !== null) {
          setUsers(users => [...users, user]);
        }
      })
    ];

    return () => subscriptions.forEach(sub => sub.unsubscribe());
  },
  [messagingService]);

  return (
    <Fragment>
      {addUserDialogActive &&
      <AddUserDialog
        onCommit={onAddUserCommit}
        onCancel={onAddUserCancel}/>}
      <div className='users-container'>
        <Link to="/stats">
          <div className='user-container'>
            <div className='user-icon'>
              <img className='user-icon'
                src={stats}
                alt='Leaderboard Chart'/>
            </div>
          </div>
        </Link>
        <div className='user-container'>
          <div className='user-icon'
            onClick={onAddUser}>
            <img className='user-icon'
              src={add_user}
              alt='Add User'/>
          </div>
        </div>
        
          {
            users.map((user, index) => {
              return <div key={index} className='user-container'>
                <img className={user.id === selectedUserId ?
                  'user-icon-selected' : 'user-icon'}
                  src={profileImages[index % 10]}
                  alt='Avatar'
                  onClick={() => onUserSelected(user)}/>
                <div className='user-name'>
                  {user.name}
                </div>
              </div>
            })
          }
        
      </div>
    </Fragment>
  );
}

// beer/projects/kegberry-app/src/app/views/users.component.ts
import { MessagingService, IGetUserResponse, IUser, IAddUserMessageData, IMessage, ISelectUserData, IAddUserResponse } from './../infrastructure/messaging.service';
import { Component, Injectable, EventEmitter, Output } from '@angular/core';
import { Subscription } from 'rxjs';

@Component({
  selector: 'users-component',
  templateUrl: 'users.component.html',
  styleUrls: ['users.component.css']
})
export class Users {
    private _users: IUser[] = [];
    private _selectedUserId: string = "";
    private _subscriptions: Subscription[];
    addUserDialogActive: boolean = false;

    @Output() userSelected = new EventEmitter();

    constructor(@Injectable() private _messagingService: MessagingService) {}

    ngOnInit(): void {
        this._subscriptions = [
            this._messagingService.readyStream.subscribe(() => {
                this.getUsers();
            }),

            this._messagingService.getUsersResponseStream.subscribe((response: IGetUserResponse) => {
                if (response !== undefined) {
                    this.users = response.users;
                }
            }),

            this._messagingService.addUserResponseStream.subscribe((user: IAddUserResponse) => {
                if (user !== undefined) {
                    this.users.push(user);
                }
            })
        ]
    }

    ngOnDestroy(): void {
        this._subscriptions.forEach(sub => sub.unsubscribe());        
    }

    get users(): IUser[] {
        return this._users;
    }

    set users(users: IUser[]) {
        this._users = users;
    }

    get selectedUserId(): string {
        return this._selectedUserId;
    }

    set selectedUserId(id: string) {
        this._selectedUserId = id;
    }

    private getUsers(): void {
        this._messagingService.sendMessage(this._messagingService.GetUsers, undefined);
    }

    addUser(username: string): void {
        let data: IAddUserMessageData = {name: username};
        this._messagingService.sendMessage(this._messagingService.AddUser, data);
    }

    onUserSelected(user: IUser): void {
        let data: ISelectUserData = {id: user.id};
        this._messagingService.sendMessage(this._messagingService.SelectUser, data);
        this.selectedUserId = user.id;
        this.userSelected.emit(user);
    }

    onAddUserCommit(username: string) {
        this.addUserDialogActive = false;
        this.addUser(username);
    }

    onAddUserCancel(_: any) {
        this.addUserDialogActive = false;
    }
}
<add-user-dialog
    *ngIf="this.addUserDialogActive"
    (commit)="onAddUserCommit($event)"
    (cancel)="onAddUserCancel($event)">
</add-user-dialog>
<div class="users-container">
    <div class="user-container">
        <a routerLink="/stats" routerLinkActive="active">
            <div class="user-icon">
                    <img class="user-icon"
                        [src]="'assets/stats.png'">
            </div>
        </a>
    </div>
    <div class="user-container">
        <div class="user-icon"
             (click)="this.addUserDialogActive = true">
             <img class="user-icon"
                  [src]="'assets/add_user.png'">
        </div>
    </div>
    <div class="user-container" *ngFor="let user of users; let i = index">
        <img [ngClass]="user.id === selectedUserId ? 'user-icon-selected' : 'user-icon'"
            [src]="'assets/profile_' + i % 10 + '.png'"
            (click)="onUserSelected(user)">
        <div class="user-name">{{user.name}}</div>
    </div>
</div>
