// beer/app/views/pour.component.ts
import { MessagingService, IPourNotification } from './../infrastructure/messaging.service';
import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';

@Component({
    selector: 'pour-component',
    templateUrl: './app/views/pour.component.html',
    styleUrls: ['./app/views/pour.component.css']
})

export class Pour {
    private _maxBeerHeight = 220;
    private _progress: number;
    private _currentUserName: string = 'default user';
    foams = Array(7).fill(0).map((x,i) => i);
    bubbles = Array(6).fill(0).map((x, i) => i);

    constructor(private _messageService: MessagingService) { 
        this.progress = 0;
        this._messageService.pourNotificationStream.subscribe((data: IPourNotification) => {
            if (data !== undefined)
            {
                this.progress = (data.totalPour*1000)/5;
                console.log('totalpour' + data.totalPour);
                console.log(this.progress);
                this.currentUserName = data.currentUser.name;

                if (data.isFinished)
                {
                    setTimeout(() => {
                        this.progress = 0;
                        this.currentUserName = 'default user'
                    }, 4000);
                }
            }
        });
    }

    get progress(): number
    {
        return this._progress
    }

    set progress(progress: number)
    {
        this._progress = progress > 100 ? 100 : progress;
    }

    get beerHeightProgress(): number {
        return this._progress * this._maxBeerHeight / 100;
        // return 220;
    }

    get currentUserName(): string
    {
        return this._currentUserName;
    }

    set currentUserName(currentUserName: string)
    {
        this._currentUserName = currentUserName;
    }
}
<div class="pour-progress">
    <ngb-progressbar type="success" [value]="this.progress" [max]=100 [striped]="true">Pouring beer for {{this.currentUserName}}...</ngb-progressbar>
    <div id="beer-pint-container">
      <div id="pint">
        <div id="liquid" [style.height.px]="beerHeightProgress">
            <div id="bubblesContainer">
                <div class="bubble" *ngFor="let bubble of bubbles"></div>
            </div>
        </div>
        <div class="beer-foam">
            <div class="foam" *ngFor="let foam of foams"></div>
        </div>
      </div>
    </div>
</div>

// beer2/src/components/Pour/Pour.tsx
import React, { useState, useEffect } from 'react';
import { useMessagingService } from '../../infrastructure/MessagingContext';
import { IPourNotification } from '../../infrastructure/MessagingService';
import './Pour.css';

export interface IPourProps {
  pourFinished(): void;
}

export function Pour({ pourFinished }: IPourProps) {
  const maxBeerHeight = 220;
  const [progress, setProgress] = useState(0);
  const foams = Array(7).fill(0).map((x,i) => i);
  const bubbles = Array(6).fill(0).map((x, i) => i);
  const messagingService = useMessagingService();

  useEffect(() => {
    messagingService.pourNotificationStream.subscribe((data: IPourNotification) => {
      if (data !== undefined) {
        const newProgress = data.totalPour*1200/5;
        setProgress(newProgress);
        console.log('totalpour' + data.totalPour);
        console.log(newProgress);

        if (data.isFinished) {
          setTimeout(() => {
              setProgress(0);
              pourFinished();
          }, 4000);
        }
      }
    })
  },
  [messagingService.pourNotificationStream, pourFinished]);

  return (
    <div className='pour-progress'>
      <div id='beer-pint-container'>
        <div id='pint'>
          <div id='liquid' style={{height: progress * maxBeerHeight / 100}}>
            <div id='bubblesContainer'>
                {bubbles.map((bubble, index) => {
                  return <div key={index} className='bubble'></div>;
                })}
            </div>
          </div>
          <div className='beer-foam'>
              {foams.map((foam, index) => {
                return <div key={index} className='foam'></div>;
              })}
          </div>
        </div>
      </div>
    </div>
  );
};
